# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\hello072\Downloads\runner4.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 170, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 240, 56, 12))
        self.label_2.setObjectName("label_2")
        self.pushButton_run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run.setGeometry(QtCore.QRect(370, 420, 151, 61))
        self.pushButton_run.setObjectName("pushButton_run")
        self.pushButton_run.clicked.connect(self.OnClickRun)
        self.pushButton_find_weight = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_find_weight.setGeometry(QtCore.QRect(580, 190, 75, 31))
        self.pushButton_find_weight.setObjectName("pushButton_find_weight")
        self.pushButton_find_weight.clicked.connect(self.OnClickFindWeight)
        self.pushButton_find_source = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_find_source.setGeometry(QtCore.QRect(580, 260, 75, 31))
        self.pushButton_find_source.setObjectName("pushButton_find_source")
        self.pushButton_find_source.clicked.connect(self.OnClickFindSource)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 310, 141, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(420, 310, 141, 21))
        self.label_4.setObjectName("label_4")
        self.textEdit_weight = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_weight.setGeometry(QtCore.QRect(240, 190, 321, 31))
        self.textEdit_weight.setReadOnly(True)
        self.textEdit_weight.setObjectName("textEdit_weight")
        self.textEdit_source = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_source.setGeometry(QtCore.QRect(240, 260, 321, 31))
        self.textEdit_source.setReadOnly(True)
        self.textEdit_source.setObjectName("textEdit_source")
        self.textEdit_iou = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_iou.setGeometry(QtCore.QRect(240, 330, 141, 31))
        self.textEdit_iou.setObjectName("textEdit_iou")
        self.textEdit_conf = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_conf.setGeometry(QtCore.QRect(420, 330, 141, 31))
        self.textEdit_conf.setObjectName("textEdit_conf")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "모델"))
        self.label_2.setText(_translate("MainWindow", "경로"))
        self.pushButton_run.setText(_translate("MainWindow", "Run"))
        self.pushButton_find_weight.setText(_translate("MainWindow", "찾기"))
        self.pushButton_find_source.setText(_translate("MainWindow", "찾기"))
        self.label_3.setText(_translate("MainWindow", "IoU Threshold"))
        self.label_4.setText(_translate("MainWindow", "Confidence Threshold"))

    def OnClickFindWeight(self):
        self.weight_path = QtWidgets.QFileDialog.getOpenFileName(self.centralwidget, "Find Weight")
        self.textEdit_weight.setText(self.weight_path[0])

    def OnClickFindSource(self):
        self.source_path = QtWidgets.QFileDialog.getExistingDirectory(self.centralwidget, "Find Source")
        self.textEdit_source.setText(self.source_path)

    def OnClickRun(self):
        str_weight = self.textEdit_weight.toPlainText()
        if len(str_weight) <= 0:
            return
        else:
            str_weight = '--weights "' + str_weight + '"'

        str_source = self.textEdit_source.toPlainText()
        if len(str_source) <= 0:
            return
        else:
            str_source = '--source "' + str_source + '"'

        str_iou = self.textEdit_iou.toPlainText()
        if len(str_iou) <= 0:
            return
        else:
            str_iou = '--iou-thres ' + str_iou

        str_conf = self.textEdit_conf.toPlainText()
        if len(str_conf) <= 0:
            return
        else:
            str_conf = '--conf-thres ' + str_conf

        str_prefix = "python detect.py --save-txt"
        str_total = str_prefix + " " + str_weight + " " + str_source + " " + str_iou + " " + str_conf
        print("실행할 명령어 : ")
        print(str_total)
        os.system(str_total)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())